[project]
name = "ci2025-lab3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "icecream>=2.1.8",
    "networkx>=3.5",
    "numpy>=2.3.4",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]
